#!/usr/bin/env node
/**
 * merge-report.mjs — regenerates MERGE.md from the harvest manifests.
 *
 * The merge report is generated rather than hand-written so it can never drift
 * from what the claw harness actually found.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const H = join(root, 'packages', 'harvest')
const BUILD = JSON.parse(readFileSync(join(H, 'build-manifest.json'), 'utf8'))
const REPO = JSON.parse(readFileSync(join(H, 'repo-manifest.json'), 'utf8'))
const TOOLS = JSON.parse(readFileSync(join(H, 'tool-catalog.json'), 'utf8'))

const n = (v) => v.toLocaleString('en-US')
const mb = (b) => `${(b / 1024 / 1024).toFixed(1)} MB`

const rows = REPO.repos
  .map(
    (r) =>
      `| \`${r.name}\` | ${r.purpose} | ${n(r.files)} | ${n(r.codeLines)} | ${mb(r.bytes)} | ${(r.extracted?.components ?? []).length} |`,
  )
  .join('\n')

const matrix = BUILD.capabilityMatrix
  .map((c, i) => `| ${i + 1} | **${c.capability}** | ${c.source} | ${c.reachmarkSurface} |`)
  .join('\n')

const models = BUILD.dataModels
  .flatMap((s) => s.detail.map((m) => `| \`${m.name}\` | ${s.repo} | ${m.fieldCount} |`))
  .join('\n')

const byCategory = Object.entries(
  TOOLS.sites.reduce((acc, s) => {
    acc[s.category] = acc[s.category] ?? { total: 0, ok: 0, blocked: 0, unreachable: 0 }
    acc[s.category].total += 1
    acc[s.category][s.status] += 1
    return acc
  }, {}),
)
  .map(([cat, c]) => {
    const state = c.blocked ? `${c.ok} live · ${c.blocked} bot-walled` : `${c.ok} live`
    return `| ${cat} | ${c.total} | ${state} |`
  })
  .join('\n')

const topComponents = BUILD.reusableComponents
  .slice(0, 12)
  .map((c) => `| \`${c.name}\` | ${c.repo} | ${c.lines} | ${c.kind} |`)
  .join('\n')

const md = `# Merge report — Reachmark Logs

> Generated by \`npm run merge:report\` from \`packages/harvest/build-manifest.json\`.
> Do not edit by hand — re-run the command instead.

**Harvest fingerprint:** \`${BUILD.fingerprint}\`  ·  **Generated:** ${BUILD.generatedAt}  ·  **Harness:** \`tools/claw/claw.py all\`

## 1. What was imported

Four upstream repositories were cloned into \`upstream/\` and merged into one monorepo. Nothing was
deleted; heavy binary sample media was pruned to keep the workspace light.

| Repository | Role | Files | Lines | Size | Components found |
| --- | --- | ---: | ---: | ---: | ---: |
${rows}

**Totals:** ${n(BUILD.totals.sourceFiles)} files · ${n(BUILD.totals.sourceLoc)} lines ·
${n(BUILD.totals.componentsDiscovered)} components · ${n(BUILD.totals.dataModels)} data models ·
${n(BUILD.totals.referenceTools)} reference tools indexed (${BUILD.totals.referenceToolsReachable} reachable on the last probe).

## 2. Target layout

\`\`\`
reachmark-logs/
├── apps/
│   ├── web/                # React 18 + Vite client  ← the Reachmark product
│   └── api/                # Express + Prisma       ← imported from AccountsBazaar
├── services/
│   └── studio/             # FastAPI render service ← imported from MoneyPrinterTurbo
├── packages/
│   └── harvest/            # generated build manifests
├── tools/
│   ├── claw/               # harvest harness        ← descended from claw-code
│   ├── sync-harvest.mjs    # manifest → client bridge
│   └── merge-report.mjs    # generates this file
├── upstream/               # the four imported repositories, verbatim
│   ├── AccountsBazaar/
│   ├── ui-builder/
│   ├── MoneyPrinterTurbo_/
│   └── claw-code/
└── docs/                   # schemas, design reference, reference-site list
\`\`\`

## 3. Capability matrix

Every harvested asset is mapped to the surface it powers. This is what stops the merge from being
four codebases in a trench coat.

| # | Capability | Source | Reachmark surface |
| ---: | --- | --- | --- |
${matrix}

## 4. Data models inherited

Read straight out of the upstream Prisma schema by the scanner. \`apps/api/prisma/schema.prisma\`
extends these with \`AssetClass\`, \`CredentialEvent\` and \`ProofArtifact\`, plus escrow fields on
\`Transaction\`.

| Model | Repository | Fields |
| --- | --- | ---: |
${models}

New in the Reachmark extension: \`AssetClass\` (social · gaming · streaming · saas), \`CredentialEvent\`
(append-only credential chain), \`ProofArtifact\` (hashed proof media), and escrow state on
\`Transaction\` (\`escrowState\`, \`releaseAt\`, \`releaseBefore\`).

## 5. Reference tool library

The operator's list of ${n(TOOLS.probed)} tools was probed live by the harness. Bot-walled sites are
recorded honestly rather than dropped.

| Category | Tools | Status |
| --- | ---: | --- |
${byCategory}

Full detail — including HTTP status, latency, probed page title and the note on how each tool feeds
this build — lives in \`packages/harvest/tool-catalog.json\` and renders at \`/tools\`.

## 6. Highest-value components to port first

Ranked by size, this is where the real logic lives in the merged sources.

| Component | Repository | Lines | Kind |
| --- | --- | ---: | --- |
${topComponents}

## 7. Design system provenance

The Reachmark token set in \`apps/web/src/styles/index.css\` is a deliberate re-ramp of what the
harness found:

* **ui-builder** — shadcn "new-york" base, the gradient hairline \`.edge\` card shell, the multi-step
  wizard engine with live validation, the field registry idea now driving the Sell wizard.
* **AccountsBazaar** — dark glass panel treatment (\`glass\`, \`glass-card\`), gradient text, custom
  scrollbars, the layout rhythm of the listing grid.
* **MoneyPrinterTurbo** — the scene/timeline vocabulary now used by the Proof Studio preview.
* **New for Reachmark** — the Framer Motion layer: page transitions, scroll-linked rails, magnetic
  tilt cards, animated counters, aurora backdrop, command palette.

## 8. Reproduce this report

\`\`\`bash
npm run claw               # scan + probe + merge + sync into the client
npm run merge:report       # regenerate MERGE.md
npm run claw:doctor        # preflight: repos present, manifests fresh
npm run build              # production build of the web client
node apps/web/scripts/smoke.mjs   # render every route through SSR and report errors
\`\`\`
`

writeFileSync(join(root, 'MERGE.md'), md)
console.log(`wrote MERGE.md (${(md.length / 1024).toFixed(1)} KB) — fingerprint ${BUILD.fingerprint}`)
